<a href="https://colab.research.google.com/github/samarthas-2601/DL_Colab/blob/main/Samartha_DL_Admission.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###2. Build a Regression MLP using Sequential API considering Admission Prediction dataset

In [ ]:
import pandas as pd
df = pd.read_csv("adission.csv")
df.head(5)

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [ ]:
df = df.drop(['Serial No.'],axis=1)
df.head(5)

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,337,118,4,4.5,4.5,9.65,1,0.92
1,324,107,4,4.0,4.5,8.87,1,0.76
2,316,104,3,3.0,3.5,8.00,1,0.72
3,322,110,3,3.5,2.5,8.67,1,0.80
4,314,103,2,2.0,3.0,8.21,0,0.65

In [ ]:
X = df.iloc[:,0:-1]
y=df.iloc[:,-1]

In [ ]:
X

     GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
0          337          118                  4  4.5   4.5  9.65         1
1          324          107                  4  4.0   4.5  8.87         1
2          316          104                  3  3.0   3.5  8.00         1
3          322          110                  3  3.5   2.5  8.67         1
4          314          103                  2  2.0   3.0  8.21         0
..         ...          ...                ...  ...   ...   ...       ...
495        332          108                  5  4.5   4.0  9.02         1
496        337          117                  5  5.0   5.0  9.87         1
497        330          120                  5  4.5   5.0  9.56         1
498        312          103                  4  4.0   5.0  8.43         0
499        327          113                  4  4.5   4.5  9.04         0

[500 rows x 7 columns]

In [ ]:
y

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ...
495    0.87
496    0.96
497    0.93
498    0.73
499    0.84
Name: Chance of Admit , Length: 500, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=0)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
import tensorflow 
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()

In [ ]:

model.add(Dense(3, activation="relu",input_dim = 7))
model.add(Dense(7, activation="relu"))
model.add(Dense(1, activation="linear"))

In [ ]:
model.compile(loss="mean_squared_error", optimizer="Adam")

In [ ]:
history = model.fit(X_train_scaled, y_train, epochs=100,  validation_split = 0.2)

Epoch 1/100
10/10 [==============================] - 1s 27ms/step - loss: 4.0767 - val_loss: 3.6965
Epoch 2/100
10/10 [==============================] - 0s 8ms/step - loss: 3.3086 - val_loss: 3.0169
Epoch 3/100
10/10 [==============================] - 0s 6ms/step - loss: 2.7049 - val_loss: 2.4772
Epoch 4/100
10/10 [==============================] - 0s 8ms/step - loss: 2.2348 - val_loss: 2.0532
Epoch 5/100
10/10 [==============================] - 0s 8ms/step - loss: 1.8639 - val_loss: 1.7218
Epoch 6/100
10/10 [==============================] - 0s 8ms/step - loss: 1.5680 - val_loss: 1.4650
Epoch 7/100
10/10 [==============================] - 0s 8ms/step - loss: 1.3406 - val_loss: 1.2597
Epoch 8/100
10/10 [==============================] - 0s 10ms/step - loss: 1.1574 - val_loss: 1.0966
Epoch 9/100
10/10 [==============================] - 0s 8ms/step - loss: 1.0081 - val_loss: 0.9653
Epoch 10/100
10/10 [==============================] - 0s 9ms/step - loss: 0.8897 - val_loss: 0.8557
Epoch 11/100
10/10 [==============================] - 0s 8ms/step - loss: 0.7934 - val_loss: 0.7646
Epoch 12/100
10/10 [==============================] - 0s 8ms/step - loss: 0.7107 - val_loss: 0.6904
Epoch 13/100
10/10 [==============================] - 0s 9ms/step - loss: 0.6443 - val_loss: 0.6277
Epoch 14/100
10/10 [==============================] - 0s 8ms/step - loss: 0.5884 - val_loss: 0.5763
Epoch 15/100
10/10 [==============================] - 0s 11ms/step - loss: 0.5421 - val_loss: 0.5328
Epoch 16/100
10/10 [==============================] - 0s 8ms/step - loss: 0.5036 - val_loss: 0.4957
Epoch 17/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4715 - val_loss: 0.4652
Epoch 18/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4437 - val_loss: 0.4411
Epoch 19/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4210 - val_loss: 0.4203
Epoch 20/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4011 - val_loss: 0.4017
Epoch 21/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3835 - val_loss: 0.3846
Epoch 22/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3672 - val_loss: 0.3686
Epoch 23/100
10/10 [==============================] - 0s 9ms/step - loss: 0.3523 - val_loss: 0.3529
Epoch 24/100
10/10 [==============================] - 0s 9ms/step - loss: 0.3373 - val_loss: 0.3380
Epoch 25/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3231 - val_loss: 0.3238
Epoch 26/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3091 - val_loss: 0.3099
Epoch 27/100
10/10 [==============================] - 0s 8ms/step - loss: 0.2955 - val_loss: 0.2959
Epoch 28/100
10/10 [==============================] - 0s 8ms/step - loss: 0.2816 - val_loss: 0.2819
Epoch 29/100
10/10 [==============================] - 0s 8ms/step - loss: 0.2680 - val_loss: 0.2676
Epoch 30/100
10/10 [==============================] - 0s 8ms/step - loss: 0.2540 - val_loss: 0.2532
Epoch 31/100
10/10 [==============================] - 0s 8ms/step - loss: 0.2399 - val_loss: 0.2390
Epoch 32/100
10/10 [==============================] - 0s 8ms/step - loss: 0.2259 - val_loss: 0.2247
Epoch 33/100
10/10 [==============================] - 0s 9ms/step - loss: 0.2118 - val_loss: 0.2103
Epoch 34/100
10/10 [==============================] - 0s 8ms/step - loss: 0.1977 - val_loss: 0.1959
Epoch 35/100
10/10 [==============================] - 0s 7ms/step - loss: 0.1836 - val_loss: 0.1815
Epoch 36/100
10/10 [==============================] - 0s 10ms/step - loss: 0.1695 - val_loss: 0.1672
Epoch 37/100
10/10 [==============================] - 0s 14ms/step - loss: 0.1557 - val_loss: 0.1531
Epoch 38/100
10/10 [==============================] - 0s 21ms/step - loss: 0.1420 - val_loss: 0.1393
Epoch 39/100
10/10 [==============================] - 0s 14ms/step - loss: 0.1285 - val_loss: 0.1260
Epoch 40/100
10/10 [==============================] - 0s 11ms/step - loss: 0.1155 - val_loss: 0.1131
Epoch 41/100
10/10 [==============================] - 0s 4ms/step - loss: 0.1029 - val_loss: 0.1008
Epoch 42/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0912 - val_loss: 0.0890
Epoch 43/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0798 - val_loss: 0.0781
Epoch 44/100
10/10 [==============================] - 0s 6ms/step - loss: 0.0694 - val_loss: 0.0682
Epoch 45/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0599 - val_loss: 0.0590
Epoch 46/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0513 - val_loss: 0.0508
Epoch 47/100
10/10 [==============================] - 0s 5ms/step - loss: 0.0437 - val_loss: 0.0436
Epoch 48/100
10/10 [==============================] - 0s 5ms/step - loss: 0.0370 - val_loss: 0.0375
Epoch 49/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0314 - val_loss: 0.0322
Epoch 50/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0266 - val_loss: 0.0280
Epoch 51/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0229 - val_loss: 0.0245
Epoch 52/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0197 - val_loss: 0.0218
Epoch 53/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0173 - val_loss: 0.0197
Epoch 54/100
10/10 [==============================] - 0s 6ms/step - loss: 0.0156 - val_loss: 0.0181
Epoch 55/100
10/10 [==============================] - 0s 6ms/step - loss: 0.0142 - val_loss: 0.0170
Epoch 56/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0133 - val_loss: 0.0161
Epoch 57/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0126 - val_loss: 0.0155
Epoch 58/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0121 - val_loss: 0.0151
Epoch 59/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0118 - val_loss: 0.0148
Epoch 60/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0115 - val_loss: 0.0146
Epoch 61/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0114 - val_loss: 0.0144
Epoch 62/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0113 - val_loss: 0.0143
Epoch 63/100
10/10 [==============================] - 0s 6ms/step - loss: 0.0112 - val_loss: 0.0142
Epoch 64/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0111 - val_loss: 0.0142
Epoch 65/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0111 - val_loss: 0.0141
Epoch 66/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0110 - val_loss: 0.0141
Epoch 67/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0110 - val_loss: 0.0140
Epoch 68/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0110 - val_loss: 0.0140
Epoch 69/100
10/10 [==============================] - 0s 5ms/step - loss: 0.0109 - val_loss: 0.0140
Epoch 70/100
10/10 [==============================] - 0s 5ms/step - loss: 0.0109 - val_loss: 0.0139
Epoch 71/100
10/10 [==============================] - 0s 5ms/step - loss: 0.0109 - val_loss: 0.0139
Epoch 72/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0108 - val_loss: 0.0139
Epoch 73/100
10/10 [==============================] - 0s 6ms/step - loss: 0.0108 - val_loss: 0.0138
Epoch 74/100
10/10 [==============================] - 0s 6ms/step - loss: 0.0108 - val_loss: 0.0138
Epoch 75/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0108 - val_loss: 0.0138
Epoch 76/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0107 - val_loss: 0.0137
Epoch 77/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0107 - val_loss: 0.0137
Epoch 78/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0107 - val_loss: 0.0137
Epoch 79/100
10/10 [==============================] - 0s 5ms/step - loss: 0.0106 - val_loss: 0.0137
Epoch 80/100
10/10 [==============================] - 0s 6ms/step - loss: 0.0106 - val_loss: 0.0136
Epoch 81/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0106 - val_loss: 0.0136
Epoch 82/100
10/10 [==============================] - 0s 6ms/step - loss: 0.0105 - val_loss: 0.0136
Epoch 83/100
10/10 [==============================] - 0s 5ms/step - loss: 0.0105 - val_loss: 0.0135
Epoch 84/100
10/10 [==============================] - 0s 7ms/step - loss: 0.0105 - val_loss: 0.0135
Epoch 85/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0105 - val_loss: 0.0135
Epoch 86/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0104 - val_loss: 0.0134
Epoch 87/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0104 - val_loss: 0.0134
Epoch 88/100
10/10 [==============================] - 0s 6ms/step - loss: 0.0104 - val_loss: 0.0134
Epoch 89/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0103 - val_loss: 0.0134
Epoch 90/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0103 - val_loss: 0.0133
Epoch 91/100
10/10 [==============================] - 0s 5ms/step - loss: 0.0103 - val_loss: 0.0133
Epoch 92/100
10/10 [==============================] - 0s 7ms/step - loss: 0.0102 - val_loss: 0.0133
Epoch 93/100
10/10 [==============================] - 0s 14ms/step - loss: 0.0102 - val_loss: 0.0132
Epoch 94/100
10/10 [==============================] - 0s 15ms/step - loss: 0.0102 - val_loss: 0.0132
Epoch 95/100
10/10 [==============================] - 0s 11ms/step - loss: 0.0101 - val_loss: 0.0132
Epoch 96/100
10/10 [==============================] - 0s 12ms/step - loss: 0.0101 - val_loss: 0.0131
Epoch 97/100
10/10 [==============================] - 0s 24ms/step - loss: 0.0101 - val_loss: 0.0131
Epoch 98/100
10/10 [==============================] - 0s 17ms/step - loss: 0.0101 - val_loss: 0.0131
Epoch 99/100
10/10 [==============================] - 0s 7ms/step - loss: 0.0100 - val_loss: 0.0130
Epoch 100/100
10/10 [==============================] - 0s 12ms/step - loss: 0.0100 - val_loss: 0.0130

In [ ]:
y_pred = model.predict(X_test_scaled)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.4712738111441005